apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: multitool
  name: multitool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multitool
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: 'false'
      labels:
        app: multitool
    spec:
      containers:
      - image: ghcr.io/eficode-academy/network-multitool
        name: network-multitool
