apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sentences
    mode: name
    version: v1
  name: name-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentences
      mode: name
      version: v1
  template:
    metadata:
      labels:
        app: sentences
        mode: name        
        version: v1
      annotations:
        dummy: '123'
        sidecar.istio.io/inject: 'false'
    spec:
      containers:
      - image: praqma/istio-sentences:v1
        name: name
        env:
        - name: "SENTENCE_MODE"
          value: "name"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sentences
    mode: name
  name: name
spec:
  ports:
  - name: http-name
    port: 5000
    protocol: TCP
    targetPort: 5000
    appProtocol: http
  selector:
    app: sentences
    mode: name
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sentences
    mode: name
    version: v2
  name: name-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentences
      mode: name
      version: v2
  template:
    metadata:
      labels:
        app: sentences
        mode: name
        version: v2
      annotations:
        dummy: '123'
        sidecar.istio.io/inject: 'false'
    spec:
      containers:
      - image: praqma/istio-sentences:v1
        name: name
        env:
        - name: "SENTENCE_MODE"
          value: "name"
        - name: "SENTENCE_NAMES"
          value: "Athos (v2),Porthos (v2),Aramis (v2),d'Artagnan (v2)"
---
