apiVersion: v1
kind: Service
metadata:
  labels:
    app: sentences
    mode: age
  name: age
spec:
  ports:
  - name: http-age
    port: 5000
    protocol: TCP
    targetPort: 5000
    appProtocol: http
  - name: http-metrics
    port: 8000
    protocol: TCP
    targetPort: 8000
    appProtocol: http
  selector:
    app: sentences
    mode: age
  type: NodePort
