apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sentences
    mode: sentence
    version: v1
  name: sentences
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentences
      mode: sentence
      version: v1
  template:
    metadata:
      labels:
        app: sentences
        mode: sentence
        version: v1
      annotations:
        sidecar.istio.io/inject: 'false'
        prometheus.istio.io/merge-metrics: 'false'
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8000'
        prometheus.io/path: '/metrics'
    spec:
      containers:
      - image: praqma/istio-sentences:v1
        name: sentences
        ports:
          - containerPort: 5000
            name: sentences
          - containerPort: 8000
            name: metrics
        env:
        - name: "SENTENCE_MODE"
          value: "sentence"
        resources:
          requests:
            cpu: 0.25
          limits:
            cpu: 0.25
