apiVersion: v1
kind: Service
metadata:
  labels:
    app: sentences
    mode: sentence
  name: sentences
spec:
  ports:
  - name: http-sentences
    port: 5000
    protocol: TCP
    targetPort: 5000
    appProtocol: http
  - name: http-metrics
    port: 8000
    protocol: TCP
    targetPort: 8000
    appProtocol: http
  selector:
    app: sentences
    mode: sentence
  type: NodePort
