apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sentences
    mode: sentence
    version: v1
  name: sentences-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentences
      mode: sentence
      version: v1
  template:
    metadata:
      labels:
        app: sentences
        mode: sentence
        version: v1
      annotations:
        dummy: '123'
        sidecar.istio.io/inject: 'false'
    spec:
      containers:
      - image: praqma/istio-sentences:v1
        name: sentences
        env:
        - name: "SENTENCE_MODE"
          value: "sentence"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sentences
    mode: sentence
    app.kubernetes.io/part-of: sentences
  name: sentences
spec:
  ports:
  - name: http-sentences
    port: 5000
    protocol: TCP
    targetPort: 5000
    appProtocol: http
  selector:
    app: sentences
    mode: sentence
  type: ClusterIP
---
