apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api
    mode: api
    version: v1
  name: api-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
      mode: api
      version: v1
  template:
    metadata:
      labels:
        app: api
        mode: api
        version: v1
    spec:
      containers:
      - image: thedukedk/sentences:v1
        imagePullPolicy: Always
        name: api
        ports:
          - containerPort: 5000
        env:
        - name: "SENTENCE_MODE"
          value: "api"
