apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: multitool
spec:
  host: multitool
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 100
      http:
        http2MaxRequests: 100
        maxRequestsPerConnection: 10
    outlierDetection:
      consecutiveErrors: 7
      interval: 30s
      baseEjectionTime: 30s
