apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: multitool
    version: v1
  name: multitool
spec:
  selector:
    matchLabels:
      app: multitool
  template:
    metadata:
      labels:
        app: multitool
        version: v1
    spec:
      containers:
      - image: praqma/network-multitool
        name: network-multitool
        ports:
          - containerPort: 80
      affinity:
        podAntiAffinity: 
          preferredDuringSchedulingIgnoredDuringExecution: 
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: multitool
              topologyKey: topology.kubernetes.io/zone
            weight: 1
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: multitool
  name: multitool
spec:
  ports:
  - port: 80
    name: http-multitool
    protocol: TCP
    targetPort: 80
  selector:
    app: multitool
  type: ClusterIP
