apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: name-route
spec:
  hosts:
  - name
  gateways:
  - mesh
  http:
  - fault:
      delay:
        percent: 100
        fixedDelay: 0.5s
    route:
    - destination:
        host: name
        subset: name-v1
 