apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sentences
    mode: age
  name: age
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentences
      mode: age
  template:
    metadata:
      labels:
        app: sentences
        mode: age
    spec:
      containers:
      - image: michaelvl/sentences:v1
        name: age
        env:
        - name: "SENTENCE_MODE"
          value: "age"
