apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sentences
    mode: name
  name: name-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentences
      mode: name
      version: v1
  template:
    metadata:
      labels:
        app: sentences
        mode: name
        version: v1
    spec:
      containers:
      - image: michaelvl/sentences:v1
        name: name
        env:
        - name: "SENTENCE_MODE"
          value: "name"
