apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sentences
    mode: sentence
  name: sentences
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentences
      mode: sentence
  template:
    metadata:
      labels:
        app: sentences
        mode: sentence
    spec:
      containers:
      - image: michaelvl/sentences:v1
        name: sentences
        env:
        - name: "SENTENCE_MODE"
          value: "sentence"
